---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tilloo-ingress
  namespace: tilloo-services
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/success-codes: 200,404
    alb.ingress.kubernetes.io/security-groups: {{ include "ingress.security-group" . }}

spec:
  rules:
    - host: tilloo4.pushspring.com
      http:
        paths:
          - path: /socket.io/
            pathType: Prefix
            backend:
              service:
                name: scheduler-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80