# TODO: Remove -test once the chart is tested as working
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: tilloo-jobs
  labels:
    name: tilloo-jobs
