apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: tilloo-services
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
    namespace: tilloo-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: tilloo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: rabbitmq
        namespace: tilloo-services
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-alpine
          ports:
            - containerPort: 5672
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 1Gi