apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: tilloo-services
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /socket.io/
    alb.ingress.kubernetes.io/success-codes: "400"
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: scheduler
    namespace: tilloo-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: tilloo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scheduler
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: scheduler
        namespace: tilloo-services
    spec:
      serviceAccountName: tilloo-admin
      containers:
        - name: scheduler
          image: ghcr.io/chriskinsman/tilloo:latest
          # env:
          # - name: DEBUG
          #   value: tilloo:*
          command: ["/tilloo/bin/scheduler.js"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /tilloo/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: tilloo-config