apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /socket.io/
    alb.ingress.kubernetes.io/success-codes: "400"
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: scheduler
    namespace: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scheduler
      namespace: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: scheduler
        namespace: {{ .Values.namespace }}
    spec:
      serviceAccountName: tilloo-admin
      containers:
        - name: scheduler
          image: {{ .Values.imageRepository | default "ghcr.io/chriskinsman/" }}/{{ .Values.imageTag | default "latest" }}
          {{ if .Values.debug }}
          env:
          - name: DEBUG
            value: tilloo:*
          {{ end }}
          command: ["/tilloo/bin/scheduler.js"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /tilloo/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: tilloo-config