apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.servicesNamespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
    namespace: {{ .Values.servicesNamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: {{ .Values.servicesNamespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
      namespace: {{ .Values.servicesNamespace }}
  template:
    metadata:
      labels:
        app: web
        namespace: {{ .Values.servicesNamespace }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: web
          image: {{ include "tilloo.image" . }}
          imagePullPolicy: IfNotPresent
          {{ if .Values.debug }}
          env:
          - name: DEBUG
            value: tilloo:*
          {{ end }}
          command: ["/tilloo/web/server/index.js"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 1Gi
          volumeMounts:
            - mountPath: /tilloo/config
              name: config-volume
            {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }} 
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: tilloo-config
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8}}
        {{- end }}