apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
    namespace: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
      namespace: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: web
        namespace: {{ .Values.namespace }}
    spec:
      serviceAccountName: tilloo-admin
      containers:
        - name: web
          image: {{ .Values.imageRepository | default "ghcr.io/chriskinsman/" }}/{{ .Values.imageTag | default "latest" }}
          {{ if .Values.debug }}
          env:
          - name: DEBUG
            value: tilloo:*
          {{ end }}
          command: ["/tilloo/web/server/index.js"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 1Gi
          volumeMounts:
            - mountPath: /tilloo/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: tilloo-config