apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: tilloo-services
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
    namespace: tilloo-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: tilloo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: web
        namespace: tilloo-services
    spec:
      serviceAccountName: tilloo-admin
      containers:
        - name: web
          image: ghcr.io/chriskinsman/tilloo:latest
          # TODO: Add debug switch to chart values/ helpers 
          # env:
          # - name: DEBUG
          #   value: tilloo:*
          command: ["/tilloo/web/server/index.js"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 1Gi
          volumeMounts:
            - mountPath: /tilloo/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: tilloo-config